export const lightTheme = {
  body: "#19223f",
  clr: "#000",
  mainBg: "#f3f3f4",
  white: " #fdfdfd",
  clrGray: "#5D5E5F",
  clrGray2: "#5D5E5F",
  selectGray: "#fff",
  tableTopColor: "#303030",
  inputBg: "#fff",
  btnActive: "#19223F",
  btnActiveClr: "#fff",
  customBtn: "#f3f3f4",
  formSelect: "#fff",
  textAriaBg: "#F9F9FA",
};

export const darkTheme = {
  body: "#19223f",
  clr: "#fff",
  mainBg: "#000",
  white: "#19223f",
  clrGray: "#fff",
  clrGray2: "gray",
  selectGray: "gray",
  tableTopColor: "#fff",
  inputBg: "transparent",
  btnActive: "#fff",
  btnActiveClr: "#000",
  customBtn: "#222a4387",
  FormSelect: "#7c7c80d6",
  textAriaBg: "#7c7c80d6",
};
